nelmio_api_doc:
    documentation:
        info:
            title: Auction API
            description: API for the Antique Items Auction Web Application
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)